apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openshift-java-demo-ingress
  namespace: openshift-java-demo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: openshift-java-demo.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openshift-java-demo-service
            port:
              number: 80
